### ISSUE TITLE
当使用ocr查找text带有重复字母的时候程序无法正确匹配到文案

### ISSUE THREAD

**Issue by q88535448** [hao1032/adbui#1]
当使用ocr查找text带有重复字母的时候（例如：ENABLE或aaaa）程序无法正确匹配到文案。
因为`min_hit = min_hit if min_hit else len(text_list)`这里没有用set，而`mix = list(set(text_list) & set(list(itemstring))) `这里都进行了set处理，当有重复的字符时mix必定小于min_hit，导致查找失败

**Comment by hao1032** [comment]
多谢反馈，新版0.3.5已经修复。
`# 计算 text_list 和 item_string_list 中相同元素的数量
for char in text_list:
    if char in item_string_list:
        item_string_list.pop(item_string_list.index(char))
        same_count += 1`
