### ISSUE TITLE
在UIautomator获取到APP的XPath，在python中无法找到该元素

### ISSUE THREAD

**Issue by zhaoyanqing624** [hao1032/adbui#5]
连着真机 OPPO android7.1.1，adb可以正常运行，xpath根据Uiautomator获得
试着运行以下代码
d = Device('2986da51')
mic_btn = d.get_ui_by_xpath('//android.widget.FrameLayout[1]/android.view.ViewGroup[2]')
mic_btn.click()
返回错误信息
NameError: dump xml fail!

**Comment by chunyuong** [comment]
@zhaoyanqing624   请手动执行adb shell  uiautomator dump  然后把文件导出来，发出来，我们来看看是什么问题。

**Comment by hao1032** [comment]
@zhaoyanqing624 出现 NameError: dump xml fail! 应该是dump失败了，可能的原因是当前手机的界面是动态的。
