### ISSUE TITLE
请教个问题：如何找到switch？

### ISSUE THREAD

**Issue by jufei** [hao1032/adbui#6]
请教几个问题：
按照我的理解，你的这个实现过程是通过ulautomator到处layout的xml文件，然后解析，来找到ui的，对吧？

现在的问题是：
1：想请问一下你那个截图里面用来看xml的是什么软件？
2. 如何获取到那些开关的UI，比如Vivo X21设置界面设置飞行模式的开关：

<node index="0" text="飞行模式" resource-id="android:id/title" class="android.widget.TextView" package="com.android.settings" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[174,585][864,650]"/>
<node index="1" text="" resource-id="com.android.settings:id/combine_relativelayout" class="android.widget.LinearLayout" package="com.android.settings" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[888,552][1032,684]">
<node index="0" text="" resource-id="com.android.settings:id/checkBox" class="android.view.View" package="com.android.settings" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[888,552][1032,684]"/>
</node>
</node>
<node index="1" text="" resource-id="com.android.settings:id/tile_divider" class="android.view.View" package="com.android.settings" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[174,688][1080,690]"/>
</node>
</node>

貌似不好找这种开关UI。

谢谢。

**Comment by hao1032** [comment]
![image](https://user-images.githubusercontent.com/4860962/87392179-ad5a2880-c5de-11ea-9d62-cff4c0aef2c1.png)
用这个软件看的
