### ISSUE TITLE
device.util.cmd('ping 127.0.0.1') 存在解码错误

### ISSUE THREAD

**Issue by bs111** [hao1032/adbui#7]
device=adbui.Device(sn=serial)    
out = device.util.cmd('ping 127.0.0.1')
  File "D:\Python36\lib\site-packages\adbui\util.py", line 47, in cmd
    out_line = p.stdout.readline().decode('utf-8').strip()  # 单行输出内容
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

**Comment by bs111** [comment]
def getSystemLanguageAndPageCode():
    dll_handle = ctypes.windll.kernel32
    sys_lang = hex(dll_handle.GetSystemDefaultUILanguage())
    sys_lang,loc_lang=locale.getdefaultlocale()
    print(sys_lang,loc_lang)#zh_CN cp936
    #我的系统是中文中国，默认是cp936 也就是GBK编码
    return sys_lang,pageCodeDict[loc_lang]
建议decode的时候不要默认是utf-8

**Comment by hao1032** [comment]
可以自己指定编码 out = d.util.cmd('ping 127.0.0.1', encoding='gbk')
